### ISSUE TITLE
Cache queries

### ISSUE THREAD

**Issue by femtotrader** [JuliaWeb/Requests.jl#101]
Hello,

I'm new to Julia. I'm a Python guy.
I wonder if Requests.jl (or any other Julia project) provides a cache mechanism (store queries and responses to database) like http://requests-cache.readthedocs.org/

Such a feature (with support of several kind of database - SQLite, MySQL, PostGreSQL ...) will be great.

Kind regards

**Comment by malmaud** [comment]
It doesn't - that sounds like functionality that would belong in another package. You can also just run a squid proxy server, and Requests will respect the HTTP_PROXY set of environment variables.

**Comment by femtotrader** [comment]
A first implementation can be found here https://github.com/femtotrader/RequestsCache.jl
It's build on top of Requests.jl and [JLD.jl](https://github.com/JuliaLang/JLD.jl)
There is still some work (unit test, continuous integration, packaging...)
I only performed some tests (sample code in fact) with GET queries. But it should be enough for my purpose, especially for [DataReader.jl](https://github.com/femtotrader/DataReader.jl)
