### ISSUE TITLE
Display HTML code as string and not as hex values

### ISSUE THREAD

**Issue by femtotrader** [JuliaWeb/Requests.jl#102]
Hello,

I'm looking at http://stackoverflow.com/questions/24229984/reading-data-from-url

I did

```julia
import Requests: get
res = get("http://julialang.org")
@printf("%s", res.data)
```

but I get something like

```
...
x69,0x76,0x3e,0x0a,0x3c,0x2f,0x64,0x69,0x76,0x3e,0x0a,0x0a,0x3c,0x2f,0x62,0x6f,0x64,0x79,0x3e,0x0a,0x3c,0x2f,0x68,0x74,0x6d,0x6c,0x3e,0x0a]
```

How to get string (HTML code) ?

Sorry for my newbie questions.

Kind regards

**Comment by malmaud** [comment]
Use `bytestring(res)`
