### ISSUE TITLE
Cookies and Facebook

### ISSUE THREAD

**Issue by blmvxer** [JuliaWeb/Requests.jl#106]
I'm trying to work on making a simple Facebook client using Julia. everytime I attempt to open Facebook through julia it telles me I don't have cookies enabled in my gui browser

**Comment by samoconnor** [comment]
If I recall correctly, it works like this: If the server sends you a `Set-Cookie:` header, you have to send the cookie back in a `Cookie:` header with subsequent requests to that server. There are a bunch of optional attributes `Domain=`, `Expires=` etc that you may also have to honour to get cookies to work with a particular service.

See examples here: https://tools.ietf.org/html/rfc6265#section-3.1

**Comment by blmvxer** [comment]
That makes much more sense. Thank you. I tried just messing with different
ways of get and push. But this helps much more

**Comment by malmaud** [comment]
Correct, Requests.jl will parse the cookies the server tells you to set, and when you issue a request you can tell it what cookies to set.  However, it has no concept of a 'session' that remembers which cookies go with what server. That would be a reasonable feature to have.

**Comment by samoconnor** [comment]
> ... concept of a 'session' that remembers which cookies go with what server. That would be a reasonable feature to have.

I would recommend putting that kind of thing in a higher-level module (`WebClient` ?). I think the Julia web stack should have more clearly defined layers.

There should be a low-level layer that does not [mess with `User-Agent`, `Accept`, `Content-Encoding`, Set-Cookie` etc](https://github.com/JuliaWeb/Requests.jl/blob/master/src/Requests.jl#L194).

Then there should be a mid-layer that does pretty much what `Requests.jl` does now but with anything to do with authentication or state removed.

Anything stateful, or anything where default settings effect implicitly define security policy should be in a higher level "browser simulation" layer (or perhaps uses should be directed towards a curl wrapper for this kind of thing?).

There are places in `AWSCore.jl` where it is desirable to avoid the default `Requests.jl` behaviours. e.g.: 

 - The AWS request [must be re-sigened on redirect](https://github.com/samoconnor/AWSCore.jl/blob/5938252aa70cbe39e338346899389efac326c536/src/AWSCore.jl#L167), and AWS has slightly non-compliant (but with good reason) redirect semantics.

 - [`Requests.open_stream` is called directly](https://github.com/samoconnor/AWSCore.jl/blob/5938252aa70cbe39e338346899389efac326c536/src/http.jl#L62) to avoid default behaviour of `do_stream_request`.
