### ISSUE TITLE
302 Redirects

### ISSUE THREAD

**Issue by texasrocks** [JuliaWeb/Requests.jl#108]
I don't know if this is a bug or a feature request, but it appears that Requests doesn't follow 302 redirects. I know they are rare, but it would probably be good to account for them.

Thanks.

Brandon

**Comment by samoconnor** [comment]
It is not possible to handle redirects in a generally correct way at the Requests.jl layer.

For example authentication headers may have to be re-written to be valid with the new URL.  https://github.com/samoconnor/AWSCore.jl/blob/master/src/AWSCore.jl#L155

**Comment by malmaud** [comment]
Still, no reason we couldn't follow 302s.

**Comment by samoconnor** [comment]
I recommend separating this kind of stateful functionality into a separate layer (or a seperate package). 
There should be a distinction between a low level stateless HTTP transport-layer API and API that emulates a command line tool like wget or curl. 
See https://github.com/JuliaWeb/Requests.jl/issues/106#issuecomment-199048507

A HTTP library can usefully provide functionaltiy that spans layers 4,5,6&7 in the OSI model, but there should be clear separation of layers in the implementation and the APIs.

**Comment by malmaud** [comment]
i don't necessarily disagree, but it doesn't seem germane to this issue - we already follow one kind of redirect, so its inconsistent not to follow 302s.

**Comment by samoconnor** [comment]
That's fair enough. I didn't realise that redirect-following had been added.

**Comment by malmaud** [comment]
Also not sure if know already @samoconnor , but you can pass `allow_redirects=false` to not have redirects automatically followed and handle them yourself.

**Comment by malmaud** [comment]
@texasrocks Are you sure it's not following 302s already? https://github.com/JuliaWeb/Requests.jl/blob/4936215e1441aeb66d47caf05f1b011776040cb3/src/Requests.jl#L253 should already be doing it.

**Comment by texasrocks** [comment]
Now that I look at it, I'm not sure what the issue is. Here is a sample link:
"https://www.fbo.gov/notices/804c99849da3f90a147ab17e94bb605c"

It looks like Requests.get follows two redirects - the first is a 302 redirect to "https://www.fbo.gov/index?s=opportunity&mode=form&tab=core&id=804c99849da3f90a147ab17e94bb605c". That's what should happen. Then there is a second redirect to "https://www.fbo.gov/index." If I cut a paste the sample link above into a browser it stops after the first redirect. That's also true with Python requests. In Julia, it follows the second redirect.

In contrast, if I do a get request for the first redirect ("https://www.fbo.gov/index?s=opportunity&mode=form&tab=core&id=804c99849da3f90a147ab17e94bb605c") and check the headers, I don't see a redirect.

I ended up writing a function to disallow redirects, but manually follow the location header and I got what I needed.  See below. Allowing redirects, however, doesn't result in the same page.

Thanks.

Brandon

function req(url)
  r = Requests.head(url, allow_redirects=false)
  h = headers(r)
  suf = get(h,"Location","missing")
  if suf == "missing"
    return url
  else
    redir = string("https://www.fbo.gov",suf)
    req(redir)
  end
end

**Comment by malmaud** [comment]
Sounds like a bug then.

**Comment by malmaud** [comment]
Fixed, [patch submitted](https://github.com/JuliaLang/METADATA.jl/pull/4994)
