### ISSUE TITLE
Running through tor?

### ISSUE THREAD

**Issue by blmvxer** [JuliaWeb/Requests.jl#109]
I am working on a Tor mapping project and have been porting my program from Python to Julia, and Have ran into the issues of not having access to proxy tools with Julia, I'm using this module specifically to test addresses. Is there anyway to use this with tor?

**Comment by malmaud** [comment]
Requests.jl will respect the HTTP_PROXY and HTTPS_PROXY environment variables. I think that should be sufficient.

**Comment by blmvxer** [comment]
I apologize, but how would I set this variable

**Comment by malmaud** [comment]
Either the same way you set any environment variable (eg, `export HTTP_PROXY=...` in the shell before starting the Julia process) or by passing `proxy` and `https_proxy` keyword options to `get`/`post`.

**Comment by blmvxer** [comment]
Sweet, thank you!
