### ISSUE TITLE
get() returns misleading result in case of EarlyEOF

### ISSUE THREAD

**Issue by josefsachsconning** [JuliaWeb/Requests.jl#112]
If the HTTP server closes the connection before writing data,

```
julia> resp = get(url);
Response(200 OK, 0 headers, 0 bytes in body)
```

**Comment by malmaud** [comment]
What behavior would you recommend?

**Comment by josefsachsconning** [comment]
I think that throwing an exception would be reasonable.

**Comment by samoconnor** [comment]
In [`AWSCore.jl/src/http.jl`](https://github.com/samoconnor/AWSCore.jl/blob/master/src/http.jl#L99) I check for `stream.state != BodyDone` and `response.status in [200, 201, 202, 204, 206]` and throw `EOFError()`.

`http.jl` also uses a [`HTTPException`](https://github.com/samoconnor/AWSCore.jl/blob/master/src/http.jl#L106) type for non 2XX status and has a [retry loop with exponential back-off](https://github.com/samoconnor/AWSCore.jl/blob/master/src/http.jl#L120) to handle `UVError` and 5XX status.

Please feel free to incorporate parts of this into Requests.jl if you think they might be generally useful.
