### ISSUE TITLE
Response cookies now in res.headers instead of res.cookies?

### ISSUE THREAD

**Issue by JockLawrie** [JuliaWeb/Requests.jl#114]
Hi there,

I have an app of the form

``` julia
function app(req, res)
    # do stuff here
    res
end
```

I am running some tests of the form `res = Requests.post(url; data = some_data)`. The response should contain a cookie with name "id". It did...until I did a `Pkg.update()` this morning.

On the server I verify the response contains the desired cookie by inserting `println(res.cookies)` before the last line of `app(req, res)`. However, on the client `res` now has no cookies and the desired cookie exists in `res.headers`, specifically a header called `S`. Is this a bug?

FYI - the example that fails is [here](https://github.com/JockLawrie/AccessControl.jl/blob/master/test/runtests.jl), the failure is on line 45.

**Comment by malmaud** [comment]
Ya that shouldnt happen. Can you give me a test I can run locally? Or maybe serialize the problematic response object to a file and share it with me?

**Comment by JockLawrie** [comment]
Below is a self-contained test case. The issue has something to do with HTTPS...the print statements give sensible results when the app is run under HTTP, but not under HTTPS. Not sure if the problem is in Requests.jl or HttpServer.jl.

```julia
using HttpServer
using Requests


function app(req::Request)
    res = Response()
    setcookie!(res, "mycookie", "some_value")
    res
end

# Run the app under HTTPS rather than HTTP
rel(filename::AbstractString, p::AbstractString) = joinpath(dirname(filename), p)
if !isfile("keys/server.crt")
    @unix_only begin
	run(`mkdir -p $(rel(@__FILE__, "keys"))`)
	run(`openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout $(rel(@__FILE__, "keys/server.key")) -out $(rel(@__FILE__, "keys/server.crt"))`)
    end
end

server = Server((req, res) -> app(req))
cert   = MbedTLS.crt_parse_file(rel(@__FILE__, "keys/server.crt"))
key    = MbedTLS.parse_keyfile(rel(@__FILE__, "keys/server.key"))
@async run(server, port = 8000, ssl = (cert, key))
sleep(1.0)


####### TEST
res = get("https://0.0.0.0:8000/"; tls_conf = Requests.TLS_NOVERIFY)
println(res.cookies)
println(res.headers)
```
