### ISSUE TITLE
Slower than requests (python)

### ISSUE THREAD

**Issue by nico202** [JuliaWeb/Requests.jl#116]
Hi, I really appreciate your work, it's nice to have this module on julia.
However, I noticed this is times slower than python requests.

Here the example script I used for testing:

requests.py
```
import requests
import timeit

def test():
    requests.get("http://192.168.1.14")

print(timeit.timeit(test, number = 100))
```

requests.jl
```
import Requests

function test()
    for i in 1:100
        Requests.get("http://192.168.1.14")
    end
end

@time test()
```

I get 0.79s vs 5s, that's 6x slower. The url exists and is in the local net

**Comment by malmaud** [comment]
Thanks! 
We have a great Google Summer of Code student who is going to look into enhancements for the Julia web packages this summer, which might address this.  It's probably not something I'll have a chance to get into myself much though.

**Comment by sorpaas** [comment]
Hi @nico202,

What operating system are you using? And what's your Julia version?

Can you perform a test with a HTTP server on localhost? I still cannot reproduce your result.

The Python version of
```
import requests
import timeit

def test():
    requests.get("http://127.0.0.1:8000")

print(timeit.timeit(test, number = 100))
```
gives me `0.244947195053`.

And the Julia version of
```
import Requests

function test()
    for i in 1:100
        Requests.get("http://127.0.0.1:8000")
    end
end

@time test()
```
gives me `0.214314 seconds (59.32 k allocations: 22.993 MB, 3.65% gc time)`.

**Comment by quinnj** [comment]
FWIW, I noticed a similar slowness on 0.4 (my case was with an https domain, but I didn't test straight http).  But 0.5 seems to be nice and speedy; not sure what would have changed, but just a datapoint to add to the discussion.

**Comment by nico202** [comment]
julia version: Version 0.4.5 (2016-03-18 00:58 UTC)
OS: NixOS x86_64

Running a local server (webpy)
julia: 0.140281 seconds (42.71 k allocations: 9.052 MB)
python: 0.211918115616

Remote
julia: 0.524065
python: 0.517185926437

I think I was running an outdated version (maybe?)
The issue can be closed, thanks :D

**Comment by malmaud** [comment]
Great
