### ISSUE TITLE
readall(resp) does not honour encoding type

### ISSUE THREAD

**Issue by bluesmoon** [JuliaWeb/Requests.jl#120]
If you have an HTTP response that is in ISO-8859-1, for example, with the correct `Content-Type` set like this: `Content-Type: application/json;charset=ISO-8859-1`, `readall` still tries to read all bytes as if they were UTF-8 and fails when it encounters characters with the high bit set.

Instead, we should read the character encoding from the `Content-Type` header and transform the stream appropriately while reading from bytes to a Julia string

**Comment by malmaud** [comment]
Good point - this would make for a good intro issue for someone wanting to contribute.

**Comment by bluesmoon** [comment]
Would make sense to use https://github.com/nalimilan/StringEncodings.jl

**Comment by samoconnor** [comment]
Related? https://github.com/JuliaWeb/Requests.jl/pull/93#issuecomment-168604416
