### ISSUE TITLE
Exporting Base.get causes surprising behavior when passing an ASCIIString instead of a Nullable

### ISSUE THREAD

**Issue by essenciary** [JuliaWeb/Requests.jl#124]
Hi, 

I'm not sure if anything has changed recently in regards to the `get` method. I seem to remember that not very long ago I used to get a warning about both `Base` and `Requests` exporting `get` and needing to use it in fully qualified form. 

I'm not getting the warning anymore, but instead I ran into a very confusing issue: 

``` julia
julia> a = Nullable{AbstractString}("foo")
Nullable("foo")

julia> b = "bar"
"bar"

julia> Base.get(b)
ERROR: MethodError: `get` has no method matching get(::ASCIIString)

julia> using Requests

julia> Base.get(b)
ERROR: Unsupported scheme "bar"
 in open_stream at /Users/adrian/.julia/v0.4/Requests/src/streaming.jl:179
 in do_stream_request at /Users/adrian/.julia/v0.4/Requests/src/Requests.jl:346
 in do_request at /Users/adrian/.julia/v0.4/Requests/src/Requests.jl:286
 in get at /Users/adrian/.julia/v0.4/Requests/src/Requests.jl:407
 in get at /Users/adrian/.julia/v0.4/Requests/src/Requests.jl:406

julia> Base.get(a)
"foo"
```

I accidentally passed a `string` to `Base.get` instead of a `Nullable` but now Requests has provided its `get` function. It was a very tricky issue as the error was bubbling up in a very unexpected place. I think exporting into `Base` another `get` function that takes as its only argument a basic Julia type like `ASCIIString` should be done very cautiously, if ever. 

-- Adrian

**Comment by ararslan** [comment]
See also @tkelman's comment on JuliaLang/julia#16832.
