### ISSUE TITLE
Document SSL API

### ISSUE THREAD

**Issue by dfdx** [JuliaWeb/Requests.jl#126]
Looks like SSL capabilities of Requests.jl aren't very well documented. E.g. one particular use case I encountered is using `Requests.jl` with self-signed certificate (see JuliaWeb/MbedTLS.jl#47 for details), but there seems to be a lot of other interesting stuff (e.g. https proxy).

Can we have it documented?

**Comment by omalled** [comment]
I second this issue. In particular, it would help me a lot if there were documentation related to the same problem ([JuliaWeb/MbedTLS.jl#47](https://github.com/JuliaWeb/MbedTLS.jl/issues/47)). Documenting the option to disable certificate validation would be perfect for me.

**Comment by omalled** [comment]
In case someone else comes across this before there is legit documentation, I've had success disabling certificate validation with a call like

`Requests.get(...; tls_conf=Requests.TLS_NOVERIFY)`
