### ISSUE TITLE
ERROR: getaddrinfo callback: unknown node or service (EAI_NONAME)

### ISSUE THREAD

**Issue by odow** [JuliaWeb/Requests.jl#131]
@samiit reports (https://github.com/odow/NEOS.jl/issues/5#issuecomment-235552787) that 
```
using Requests
get("www.google.com")
```
results in this error
```
ERROR: getaddrinfo callback: unknown node or service (EAI_NONAME)
 in getaddrinfo at ./socket.jl:599
 in open_stream at /home/sam/.julia/v0.4/Requests/src/streaming.jl:184
 in do_stream_request at /home/sam/.julia/v0.4/Requests/src/Requests.jl:346
 in do_request at /home/sam/.julia/v0.4/Requests/src/Requests.jl:286
 in get at /home/sam/.julia/v0.4/Requests/src/Requests.jl:407
 in get at /home/sam/.julia/v0.4/Requests/src/Requests.jl:406
```
Maybe similar to https://github.com/JuliaWeb/Requests.jl/issues/87?

**Comment by malmaud** [comment]
You need 'http://' in front.

**Comment by odow** [comment]
Sorry @malmaud but I made a typo. He did have the "http://" at the front. See https://github.com/odow/NEOS.jl/issues/5#issuecomment-235416575

I think this is still unresolved.

**Comment by malmaud** [comment]
#87  was fixed. Unless someone else can reproduce this, I don't think there's anything we can do.

**Comment by samiit** [comment]
I migrated to Ubuntu 16 and don't have [this issue](https://github.com/odow/NEOS.jl/issues/5) anymore.
