### ISSUE TITLE
Basic auth broken?

### ISSUE THREAD

**Issue by xpqz** [JuliaWeb/Requests.jl#132]
I think basic auth is broken; see 

https://github.com/JuliaWeb/Requests.jl/blob/master/src/Requests.jl#L218

```
headers["Authorization"] = "Basic $(encode(Base64, uri.userinfo))"
```

should be  

```
headers["Authorization"] = "Basic $(bytestring(encode(Base64, uri.userinfo)))"
```

**Comment by malmaud** [comment]
This is fixed now, right? Let me know if it isn't.
