### ISSUE TITLE
Issue with vector parameter (and comma in parameters)

### ISSUE THREAD

**Issue by mobius-eng** [JuliaWeb/Requests.jl#135]
When forming requests to services like Google Maps or similar the geographical location is usually denoted using `latitude,longitude`, for example:

```
https://www.google.co.za/maps/@-33.8545742,18.6634133,16z
```

or in GET request for @WhereIsMyTransport

```
GET api/stops?point=-33.925430,18.436443&radius=1750
```

I couldn't find a way to do it in Requests. If I use vector as a value for `point` key, I get:

```
GET api/stops?point=-33.925430&point=18.436443&radius=1750
```

Does it even make sense to pass values in succession like that?

If I put the coordinates into the string directly, the comma is escaped and becomes

```
GET api/stops?point=-33.925430%2C18.436443&radius=1750
```

Proposed solutions:
1. Change how the request string is formed for vectors. Downside: if current behaviour is sensible, this can break things.
2. Add, perhaps, the way to operate on tuples?
3. More radical: in `format_query_str` pass the control to a generic function, say, `format_query_value` that will dispatch on the type of value. So, that it can be extended with other types. Might be a bit of an overkill though as RESTful API is not that sophisticated.

For point 1, solution would be to change `format_query_str` to:

``` julia
function format_query_str(queryparams; uri = URI(""))
    query_str = isempty(uri.query) ? string() : string(uri.query, "&")

    for (k, v) in queryparams
        if isa(v, Array)
            query_str *= string("$(URIParser.escape(string(k)))=", join(map(vi -> "$(URIParser.escape(string(vi)))", v), ",") * "&")
        else
            query_str *= "$(URIParser.escape(string(k)))=$(URIParser.escape(string(v)))&"
        end
    end
    info("Query string: ", query_str)
    chop(query_str) # remove the trailing &
end
```

**Comment by nico202** [comment]
Hi, I can say that it make sense to pass it as two same named fields. Here is [why](http://stackoverflow.com/questions/24059773/correct-way-to-pass-multiple-values-for-same-parameter-name-in-get-request).

However, I think that it makes sense to have both the behaviors available, and maybe treat differently tuple and arrays

**Comment by mobius-eng** [comment]
Ok, I see. Also, considering some people might have relied on this way of passing multiple parameters, it won't be advisable to break what works.

So, the question is, what would be a preferred way to add the ability to pass multiple values via comma? I see it as either of the two:

- Add tuples as a special case.
- Make it more generic and allow other types to format themselves as they need to be formatted for a particular RESTful API. This can be done via `format_query_entry(key, value)`: default implementation would be as now: `"$(URIParser.escape(string(key)))=$(URIParser.escape(string(value)))"`; for arrays, again as it is now: `join(map(vi -> "$(URIParser.escape(string(key)))=$(URIParser.escape(string(vi)))", value), "&")`; it can be extended to tuples to do the comma separated values: `string("$(URIParser.escape(string(key)))=", join(map(vi -> "$(URIParser.escape(string(vi)))", value), ","))`; and finally if anyone wants to roll their own - they would just need to specialise that function. I can implement this if this solution is acceptable.
