### ISSUE TITLE
Can not send form data while uploading files

### ISSUE THREAD

**Issue by tanmaykm** [JuliaWeb/Requests.jl#139]
Sending form data along with files doesn't seem to be allowed:

```
ERROR: LoadError: Multiple body options specified. Please only specify one
 in #do_stream_request#23(::Dict{String,String}, ::Void, ::Dict{String,String}, ::Void, ::Array{Requests.FileParam,1}, ::Void, ::Dict{Any,Any}, ::Bool, ::Int64, ::Array{HttpCommon.Response,1}, ::MbedTLS.SSLConfig, ::Bool, ::Nullable{URIParser.URI}, ::Nullable{URIParser.URI}, ::Requests.#do_stream_request, ::URIParser.URI, ::String) at /home/tan/.julia/v0.6/Requests/src/Requests.jl:284
 in (::Requests.#kw##do_stream_request)(::Array{Any,1}, ::Requests.#do_stream_request, ::URIParser.URI, ::String) at ./<missing>:0
 in #do_request#22(::Array{Any,1}, ::Function, ::URIParser.URI, ::String) at /home/tan/.julia/v0.6/Requests/src/Requests.jl:290
 in (::Requests.#kw##do_request)(::Array{Any,1}, ::Requests.#do_request, ::URIParser.URI, ::String) at ./<missing>:0
 in #post#35(::Array{Any,1}, ::Function, ::URIParser.URI) at /home/tan/.julia/v0.6/Requests/src/Requests.jl:413
 in (::Requests.#kw##post)(::Array{Any,1}, ::Requests.#post, ::URIParser.URI) at ./<missing>:0
 in #post#34(::Array{Any,1}, ::Function, ::String) at /home/tan/.julia/v0.6/Requests/src/Requests.jl:412
 in (::Requests.#kw##post)(::Array{Any,1}, ::Requests.#post, ::String) at ./<missing>:0
...
```

In this case, `post` was called with `headers`, `data`, and `files`. The error is thrown by `@check_body` which allows only one of `json`, `data` or `files` to be specified.

May be the current implementation of `multipart/form-data` needs to be enhanced to work with parts other than files?

**Comment by quinnj** [comment]
I mean, a request can only have one body, right? Why are you trying to set/send both `data` and `files`?

**Comment by tanmaykm** [comment]
The requirement was an application that had a complex form with regular text fields and also a file to be uploaded.

I referred to this: https://tools.ietf.org/html/rfc7578 which seems to suggest that it should be possible.

**Comment by quinnj** [comment]
FWIW, HTTP.jl now handles this by allowing the user to do `HTTP.post(uri; body=Dict("key"=>"value", "file"=>open(filename)))`, i.e. passing in a Dict w/ key-value String pairs being treated as normal form data, and IO-types being uploaded as files.

**Comment by tanmaykm** [comment]
Thanks, I'll check out `HTTP.jl`.

**Comment by nico202** [comment]
Any news on this?
