### ISSUE TITLE
Ability to see request before sending

### ISSUE THREAD

**Issue by randyzwitch** [JuliaWeb/Requests.jl#14]
It'd be great to have a way to understand what the request looks like instead of just sending it. For example, Twitter provides this example, but after receiving 403 errors as the response, I have no good way to validate that my POST request matches this:

```julia
POST /oauth2/token HTTP/1.1
Host: api.twitter.com
User-Agent: My Twitter App v1.0.23
Authorization: Basic eHZ6MWV2RlM0d0VFUFRHRUZQSEJvZzpMOHFxOVBaeVJn
                     NmllS0dFS2hab2xHQzB2SldMdzhpRUo4OERSZHlPZw==
Content-Type: application/x-www-form-urlencoded;charset=UTF-8
Content-Length: 29
Accept-Encoding: gzip

grant_type=client_credentials
```

**Comment by sbromberger** [comment]
Perhaps bikeshedding here, but what if there were a kwarg "; dryrun=false" for each function that performed this task?

**Comment by malmaud** [comment]
There is a new method, `requestfor(::Response)`, that will return the request object that corresponds to the given Response.
