### ISSUE TITLE
Sending multiple fields with same name not allowed

### ISSUE THREAD

**Issue by tanmaykm** [JuliaWeb/Requests.jl#140]
It is not possible to send multiple values for the same name. That seems to be because `data` and `query` parameters must be `Associative` to be treated as form data (`parse_request_data`).

HTTP spec does not prevent it, but implementation is left to the server. Sending delimited values is the alternative. So, it's not a big issue in most cases.

But it may be good to allow a `name=>value` list also for `data` and `query`.

**Comment by quinnj** [comment]
From the docs, I think you can just pass an array of values for a single key to get a multi-value query parameter
```julia
get("http://httpbin.org/get"; query = Dict("title" => "page1"))
get("http://httpbin.org/get"; query = Dict("multi" => ["value1", "value2"]))
```
Not sure what you mean w/ the `data` parameter which is more about the body?

**Comment by tanmaykm** [comment]
Yes. Thanks. I don't know how I missed this earlier.

Form `data` also seems to be addressed in the same manner here: https://github.com/JuliaWeb/Requests.jl/blob/cf778031780fe006844103b15dff6e9e85166305/src/Requests.jl#L361
