### ISSUE TITLE
double encoding of query strings

### ISSUE THREAD

**Issue by Alexander-Barth** [JuliaWeb/Requests.jl#157]
It seems that the query strings a doubly encoded. The colon sign (:) of the query parameter startTime (see below) should be encoded as "%3A", but it is encode again and transformed in to %253A by encoding again the % sign.

Below are the steps to reproduce the issue.

```
using Requests
s = get("http://podaac.jpl.nasa.gov/ws/search/granule"; query = Dict("datasetId" => "PODAAC-GHVRS-2PO03", "startTime" => "2016-01-01T01:01:00Z", "endTime" => "2017-01-01T01:01:00Z", "itemsPerPage" => 1, "bbox" => "7.5,41.9,12.3,44.6", "sortBy" => "timeAsc", "startIndex" => 1))
s.request
```

Nullable{HttpCommon.Request}(Request(https://podaac.jpl.nasa.gov/ws/search/granule?sortBy=timeAsc&startTime=2016-01-01T01%253A01%253A00Z&datasetId=PODAAC-GHVRS-2PO03&itemsPerPage=1&startIndex=1&bbox=7.5%252C41.9%252C12.3%252C44.6&endTime=2017-01-01T01%253A01%253A00Z, 3 headers, 0 bytes in body))

```

I am using Requests version 0.4.1 and Julia 0.5.1.

**Comment by quinnj** [comment]
FWIW, in `HTTP` (successor package to Requests.jl), the colong (:) doesn't get doubly encoded,
```julia
julia> s = HTTP.URI("http://podaac.jpl.nasa.gov/ws/search/granule"; query = Dict("datasetId" => "PODAAC-GHVRS-2PO03", "startTime" => "2016-01-01T01:01:00Z", "endTime" => "2017-01-01T01:01:00Z", "itemsPerPage" => 1, "bbox" => "7.5,41.9,12.3,44.6", "sortBy" => "timeAsc", "startIndex" => 1))
HTTP.URI("http://podaac.jpl.nasa.gov/ws/search/granule?sortBy=timeAsc&startTime=2016-01-01T01%3A01%3A00Z&datasetId=PODAAC-GHVRS-2PO03&itemsPerPage=1&startIndex=1&bbox=7.5,41.9,12.3,44.6&endTime=2017-01-01T01%3A01%3A00Z")
```
but one issue I saw is that in the original URL you provided, it actually gets redirected and for the "redirect" URL, the server is responding w/
```julia
[HTTP - 2017-04-29T16:46:54.468]: redirecting to https://podaac.jpl.nasa.gov/ws/search/granule?sortBy=timeAsc&startTime=2016-01-01T01%253A01%253A00Z&datasetId=PODAAC-GHVRS-2PO03&itemsPerPage=1&startIndex=1&bbox=7.5,41.9,12.3,44.6&endTime=2017-01-01T01%253A01%253A00Z
```
so the URL _they_ provide is doubly encoded. But in redirecting to that URL, I still get a successful response. If I change the request to 
```julia
julia> s = HTTP.get("https://podaac.jpl.nasa.gov/ws/search/granule"; query = Dict("datasetId" => "PODAAC-GHVRS-2PO03", "startTime" => "2016-01-01T01:01:00Z", "endTime" => "2017-01-01T01:01:00Z", "itemsPerPage" => 1, "bbox" => "7.5,41.9,12.3,44.6", "sortBy" => "timeAsc", "startIndex" => 1), verbose=true)
```
I don't get hte redirect and get the same response.

**Comment by Alexander-Barth** [comment]
You are right that the problem is related to the redirect from http to https. All works fine, if I use directly https (which solves the issue for me). Also the HTTP package works with http and https.

Thank you these great packages and your help!
