### ISSUE TITLE
slow get operation

### ISSUE THREAD

**Issue by brzkhv** [JuliaWeb/Requests.jl#174]
Hi. I am not sure if it is a issue or not but I use a very simple script to get a url:
"
usng Requests
get(url)
"

on average running this script is 5 to 8 times slower than a python equivalent.
Is there something I am missing?

**Comment by nico202** [comment]
isn't it because of **hiw** julia works?   The second time you call get inside the same script should be faster, remember to use @time to time things

**Comment by brzkhv** [comment]
thanks. I know it seems an inappropriate way of test, but I wanted to get a simple comparison.
I have done both test on REPL and the gap is narrower now but python is still about 50% faster.

Python: start = time.time(); requests.get("https://julialang.org/"); print(time.time() - start)
Julia: @time get("https://julialang.org/")

even in each invocation for a language timing is variable very much but on average python is faster.
However julia is fast enough for my needs, but I was hoping to get the same speed

**Comment by VenkatSubramaniam** [comment]
I just ran this test as well and for some reason, even the second/third/fourth runs of the same request are still slower than the python equivalent. This deosn't seem to be because of how Julia works, per se, as far as I'm aware.

**Comment by nico202** [comment]
Try with the HTTP.jl package, for what I know it's better than Requests.jl, and I get performances 40% better than python
 @time HTTP.get("https://julialang.org/");                                                                                                                                                 
  0.134049 seconds

**Comment by brzkhv** [comment]
Thanks for the recommendation. I will try it very soon
