### ISSUE TITLE
Changes for Julia 1.0?

### ISSUE THREAD

**Issue by wherrera10** [JuliaWeb/Requests.jl#177]
Julia 1.0 has some issues with the syntax of the structure definitions used by Requests, such as the type keyword used to define a struct on line 38 of Requests.jl:
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.0.0 (2018-08-08)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using Requests
[ Info: Precompiling Requests [df88083b-ffd0-5ec9-9f27-0a3b3d809c9f]
ERROR: LoadError: syntax: extra token "GlobalSettings" after end of expression
Stacktrace:
 [1] include at .\boot.jl:317 [inlined]
 [2] include_relative(::Module, ::String) at .\loading.jl:1038
 [3] include(::Module, ::String) at .\sysimg.jl:29
 [4] top-level scope at none:2
 [5] eval at .\boot.jl:319 [inlined]
 [6] eval(::Expr) at .\client.jl:389
 [7] top-level scope at .\none:3
in expression starting at C:\Users\William\.julia\packages\Requests\JGYh8\src\Requests.jl:38

**Comment by s-celles** [comment]
`README.md` states that

```
This package is DEPRECATED
We recommend that you use HTTP.jl instead. This package is no longer maintained and has reduced functionality and performance compared to HTTP.jl.
```

So you should probably consider using https://github.com/JuliaWeb/HTTP.jl

**Comment by wherrera10** [comment]
Okay. I will miss the json= named argument handling.

**Comment by malmaud** [comment]
I think HTTP.jl would be very receptive to a feature like that if it doesn't have one already - I would open a feature request on that repo.
