### ISSUE TITLE
Archive repository

### ISSUE THREAD

**Issue by Nosferican** [JuliaWeb/Requests.jl#179]

**Comment by quinnj** [comment]
It'd probably be good to see what packages still have Requests.jl has a dependency and we can help port them to HTTP.jl before archiving here.

**Comment by Nosferican** [comment]
I just checked. No registered package for Julia 1. Has Requests.jl in the dependencies.

**Comment by quinnj** [comment]
Oh, that's great! kk, I'll archive it then.
