### ISSUE TITLE
Periodically writing results to file?

### ISSUE THREAD

**Issue by randyzwitch** [JuliaWeb/Requests.jl#19]
Is there a way to periodically write the results to a file? I'm trying to use the Twitter streaming API, so there's no real "end" to the result set. I tried the following, with no luck:

```julia

#Function that does properly formatted OAuth Twitter call
function post_statuses_filter(; options = Dict())
    r = post_oauth("https://stream.twitter.com/1.1/statuses/filter.json", options)
end

#Open a file connection
tweettest = open("/Users/randyzwitch/Desktop/tweets.txt", "w")

#Write data to file
write(tweettest, post_statuses_filter(; options = {"track" => "#oscars"}))

```

I guess what I'm looking for is either a way to specify how long to keep the connection open and write to an in-memory object such as `r` above or a way to continuously write to text file as the data streams in.

**Comment by sbromberger** [comment]
@randyzwitch is this still an issue? Should I close it or tag it "enhancement"?

**Comment by randyzwitch** [comment]
I definitely think it's still a worthwhile feature to add in, I just don't know how to do it

**Comment by malmaud** [comment]
@Keno still interested in working on a streaming API?

**Comment by malmaud** [comment]
I've begun work on a streaming API, https://github.com/JuliaWeb/Requests.jl/pull/70, that will be able to handle this use case.

**Comment by malmaud** [comment]
The 'Streaming API' section of the README has a working example of doing this now.

**Comment by randyzwitch** [comment]
Thanks, look forward to checking it out!
