### ISSUE TITLE
Do you support Http Compression ?

### ISSUE THREAD

**Issue by nhenin** [JuliaWeb/Requests.jl#21]
I have trying somtehing like that :

 Requests.get("http://web.something.com/users"; headers = {"Accept-Encoding" => "gzip,deflate"} ) 

It does not seem to compress.

**Comment by quinnj** [comment]
Wouldn't adding the `Accept-Encoding: gzip, deflate` header just return raw gzipped data instead of uncompressed? Is the enhancement here to auto-unzip the data upon receipt?

**Comment by malmaud** [comment]
Closed via https://github.com/JuliaWeb/Requests.jl/commit/42da843faf25e190eeddc71e537662dfecb2346a.
