### ISSUE TITLE
HTTP headers are not unique

### ISSUE THREAD

**Issue by staticfloat** [JuliaWeb/Requests.jl#36]
We can't use a dict to represent headers, as a server can send back multiples of headers, such as `Set-Cookie`, which need to get merged together, possibly by higher logic.  E.g. `github.com` sets:

```
Set-Cookie: user_session=JuN1cxdfprx8gJvQOOIYN6_DTuMGOBcmRF-BH7D-Zp8yIxtQU__NSZeOWLU2SvUew98aOqu3mHrnwPvh; path=/; expires=Fri, 12-Sep-2014 00:46:01 GMT; secure; HttpOnly
Set-Cookie: logged_in=yes; domain=.github.com; path=/; expires=Tue, 29-Aug-2034 00:46:01 GMT; secure; HttpOnly
Set-Cookie: dotcom_user=staticfloat; domain=.github.com; path=/; expires=Tue, 29-Aug-2034 00:46:01 GMT; secure; HttpOnly
Set-Cookie: _gh_sess=cyJsYXN0X3dyaXRlIjoxNDA5MjczMTYxNzU5LCJzZXNzaW9uX2lkIjoiYmZhNDdlM2U2NWQ2M2ZhODkxMjNiM2YyOWIxN2U5YjgifQ%3D%3D--9a25437789d4646087d3b682468db8047f3e2533; path=/; secure; HttpOnly
```

And expects to get back in following requests:
```
Cookie: tz=America%2FNew_York; user_session=JuN1cxdfprx8gJvQOOIYN6_DTuMGOBcmRF-BH7D-Zp8yIxtQU__NSZeOWLU2SvUew98aOqu3mHrnwPvh; logged_in=yes; dotcom_user=staticfloat; _gh_sess=cyJsYXN0X3dyaXRlIjoxNDA5MjczMTYxNzU5LCJzZXNzaW9uX2lkIjoiYmZhNDdlM2U2NWQ2M2ZhODkxMjNiM2YyOWIxN2U5YjgifQ%3D%3D--9a25437789d4646087d3b682468db8047f3e2533
```

**Comment by sbromberger** [comment]
Bumping this because I believe it's related to #41.

**Comment by sbromberger** [comment]
@staticfloat can you check this now and see whether it's still an issue? If it is then we'll probably want to prioritize a fix since not being able to handle multiple cookies is a fairly serious deficiency.

**Comment by staticfloat** [comment]
@sbromberger I believe it still is.  My test case is the same as in this issue; I use [this script](https://gist.github.com/staticfloat/6797876c0758525588e0) to attempt to login to github, but fail due to the headers not being merged correctly.  I can try to take a look at fixing this in the next few days.  Thank you for helping to fix the stream issues in GnuTLS; I couldn't look at this until those were fixed!

**Comment by staticfloat** [comment]
So a basic problem here (and the reason websites use multiple headers to deal with cookies like this) is that if you want to set different values with different expiration dates, you have to use multiple headers.  I don't know a good way to get around this other than changing from a Dict to an array for representing headers, but that sounds like a terrible change, so I'm going to make some "best effort" cookie header merging code and see what it looks like.

**Comment by sbromberger** [comment]
Why couldn't we default to a dict of (AbstractString) vectors? That seems like it would preserve performance as well as ensuring input flexibility.

**Comment by staticfloat** [comment]
That's also an idea, but I have no idea how much code that would break.  I'll work up a quick PR based on the quick-n-dirty fix suggested above, and then maybe we can discuss how to do it properly in that PR thread.

**Comment by malmaud** [comment]
IMO we should just do what [Python Requests does](http://www.python-requests.org/en/latest/user/quickstart/#cookies) and special-case cookies: instead of setting and getting cookies via `headers[]`, you deal them via `cookies[]`.

**Comment by malmaud** [comment]
I've special-cased the handling of the Set-Cookie header in https://github.com/JuliaWeb/Requests.jl/pull/63. While theoretically any header could be duplicated, that seems to be the only one anyone cares about in practice. Please reopen that isn't the situation for your usecase.
