### ISSUE TITLE
Unicode woes

### ISSUE THREAD

**Issue by jiahao** [JuliaWeb/Requests.jl#44]
### Problems with percent-encoded queries

Requests uses URIs under the hood since it relies on URIParser. Strictly speaking, URIs are not allowed to have Unicode characters in them, but instead require most characters to be [percent-encoded](http://en.wikipedia.org/wiki/Percent-encoding). However, there is currently something wrong with how percent-encoded data is handled.

Consider the URI

```
http://nominatim.openstreetmap.org/search?format=json&q=%E6%B7%B1%E5%9C%B3
```

where the query value (after `q=`) is percent encoding for "深圳" (Shenzhen). If I paste this string into my Chrome browser's address bar, it automatically gets converted to

```
http://nominatim.openstreetmap.org/search?format=json&q=深圳
```

However, the equivalent request

```get("http://nominatim.openstreetmap.org/search", query=Dict("format"=>"json","q"=>"%E3%82%A2"))```

returns an empty response.

I can hack URIParser to allow `URI.query` to be of type `String` instead of `ASCIIString`, in which case

```get("http://nominatim.openstreetmap.org/search", query=Dict("format"=>"json","q"=>"深圳"))```

works as expected, but then the `URI` object being constructed and used under the hood is no longer standards compliant.

I've tried looking under the hood and it looks like there is the function `format_query_str` exists to handle non-`ASCIIString` queries, but this never seems to get called with `q=深圳`. With `q=%E3%82%A2` it gets called and gets percent-encoded a second time into `q=%25E6%25B7%25B1%25E5%259C%25B3`, which makes me very sad.

In the longer term, we can consider switching over to IRIs, which allow native UTF-8 encoding.

cc @Keno

**Comment by sbromberger** [comment]
@jiahao Just curious as to whether https://github.com/JuliaWeb/URITemplate.jl might help here. Could you test it and see if it does what you need?

**Comment by jiahao** [comment]
Unfortunately not; it cannot handle even the most basic of Unicode-related tasks:

```jl
julia> URITemplate.pctencode("Montréal")
ERROR: MethodError: `pctencode` has no method matching pctencode(::UTF8String)
```

**Comment by jiahao** [comment]
Anything with a non-ASCII query is basically screwed:

```jl
julia> get(URI(http://nominatim.openstreetmap.org/search?format=json&q=Montr%E9al))
Response(400 Bad Request, 14 Headers, 383 Bytes in Body)

julia> ans.data
"<html><body><h1>Bad Request</h1><p>Nominatim has encountered an error with your request.</p><p><b>Details:</b> Illegal query string (not an UTF-8 string): Montr蠬</p><p>If you feel this error is incorrect feel free to report the bug in the <a href=\"http://trac.openstreetmap.org\">OSM bug database</a>. Please include the error message above and the URL you used.</p>\n</body></html>\n"
```

**Comment by malmaud** [comment]
I believe https://github.com/JuliaWeb/URIParser.jl/pull/22 fixes this. Reopen if you still have issues.
