### ISSUE TITLE
Incorrect type of Response.data for binary results?

### ISSUE THREAD

**Issue by jiahao** [JuliaWeb/Requests.jl#45]
As discussed in JuliaLang/julia#10274, `Response.data` cannot always be guaranteed to return a valid UTF8 string since an HTTP request can return arbitrary binary data. Typing the result as a UTF8String can cause downstream errors due to having an invalid string.

```jl
julia> using Requests; get("https://avatars.githubusercontent.com/u/744556?v=3")
Response(200 OK, 28 Headers, 29365 Bytes in Body)

julia> ans.data
"\U1a01df90JFIF\0\x01\x01\0\0\x01\0\x01\0\0\U3bfba092EATOR: gd-jpeg v1.0 (using IJG JPEG v80), quality = 90\n\U18fc0f83\x02\x02\x03\x02\x02\x03\x03\x03\x03\x04\x03\x03\x04\x05\b\x05\x05\x04\x04\x05\n\a\a\x06\b\f\n\f\f\v\n\v\v\r\x0e\x12\x10\r\x0e\x11\x0e\v\v\x10\x16\x10\x11\x13\x14\x15\x15\x15\f\x0f\x17\x18\x16\x14\x18\x12\x14\x15\x14\U18fc0fc3\x04\x04\x05\x04\x05\t\x05\x05\t\x14\r\v\r\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\x14\Ufdf8f181ʁʃ\x01\"\0\x02\x11\x01\x03\x11\x01\U1f9cf80\x01\x05\x01\x01\x01\x01\x01\x01\0\0\0\0\0\0\0\0\x01\x02\x03\x04\x05\x06\a\b\t\n\v\U2033380\x02\x01\x03\x03\x02\x04\x03\x05\x05\x04\x04\0\0\x01}\x01\x02\x03\0\x04\x11\x05\x12!1A\x06\x13Qa\a\"q\x142���\b#B�\Uffffffd5RҰ\$3br�\t\n\x16\x17\x18\x19\x1a%&'()*456789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz�����������������������������������ÃŅǇ\u249˒\u514֖\u618ښ⣣妦詩벲\U135db6\U239eba\U1f9cfc0\x03\x01\x01\x01\x01\x01\x01\x01\x01\x01\0\0\0\0\0\0\x01\x02\x03\x04\x05\x06\a\b\t\n\v\U20333c0\x02\x01\x02\x04\x04\x03\x04\a\x05\x04\x04\0\x01\x02w\0\x01\x02\x03\x11\x04\x05!1\x06\x12AQ\aaq\x13\"2�\b\x14B���\Uffffffc9#3R\Ufff94872ϊ\x16\$4\Ufffff9b1\x17\x18\x19\x1a&'()*56789:CDEFGHIJSTUVWXYZcdefghijstuvwxyz������������������������������������ÃŅǇ\u249˒\u514֖\u618ښ㤤槧骪󴵵\U1f8e79\U4017f8c\x03\x01\0\x02\x11\x03\x11\0?\0???ү+�\Ue0429J��\f�_\x18z�\\#뼪ӄ0\x02��ܴԱ0�\x0f�\0\$�ː\x0fZ\n쳝󱟘Error showing value of type UTF8String:
ERROR: invalid UTF-8 character index
 in next at ./utf8.jl:68
 in print_escaped at string.jl:869
 in show at string.jl:69
 in anonymous at show.jl:1160
 in with_output_limit at ./show.jl:1137
 in showlimited at show.jl:1159
 in writemime at replutil.jl:2
 in display at REPL.jl:117
 in display at REPL.jl:120
 in display at multimedia.jl:149
 in print_response at REPL.jl:139
 in print_response at REPL.jl:124
 in anonymous at REPL.jl:586
 in run_interface at ./LineEdit.jl:1379
 in run_frontend at ./REPL.jl:818
 in run_repl at ./REPL.jl:169
 in _start at ./client.jl:400

julia> versioninfo()
Julia Version 0.3.7-pre+1
Commit d15f183 (2015-02-17 22:12 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin14.1.0)
  CPU: Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> Pkg.installed("Requests")
v"0.0.8"
```

**Comment by sbromberger** [comment]
What's the appropriate type to use for HTTP responses?

**Comment by jiahao** [comment]
It should be an array of bytes. Maybe an `IOBuffer`?

**Comment by sbromberger** [comment]
That seems fairly straightforward, esp. since GnuTLS readall/readavailable returns an array of UInt8.

**Comment by sbromberger** [comment]
I wonder what will break if we make this change, though.

**Comment by jiahao** [comment]
Serious question: who uses the Julia web stack? Just about everything in it breaks the moment it has to deal with Unicode or general binary data.

**Comment by sbromberger** [comment]
It's a good question. I don't know the answer except to suggest "whoever is, probably shouldn't".

IMO, the fragility of the web stack is one of the main things hindering adoption of Julia outside the scientific / technical community (who might mainly be using ijulia / juliabox / repl). If we're going to get Julia in the hands of "general" programmers, we need easy-to-use networking capability, including the ability to retrieve and serve data.

We're not there yet, by a long shot. It will probably require a rewrite of the core functions (that is, GnuTLS and Requests) before moving on to HttpServer.

**Comment by jiahao** [comment]
It's a genuine concern for people who want to do data science too.

Would you be interesting in being a GSoC mentor if we get an interested student?

**Comment by sbromberger** [comment]
I could certainly help (subject to time constraints). I've already submitted the proposal to the Julia GSOC page: https://github.com/JuliaLang/julialang.github.com/blob/master/gsoc/2015/index.md#project-web-stack--networking-improvements

**Comment by quinnj** [comment]
To be fair, @jiahao, the data is returned just fine, it's just the `show` method that's throwing the error. You still technically have the data and could do a manual conversion of the `result.data.data` byte array. I agree though that the response should probably have a smarter typing structure.

**Comment by sbromberger** [comment]
...just to update, NumFocus got 3 GSoC slots. Despite JuliaWeb being tied for second place in the scoring, it is unlikely to receive a slot. (JuliaQuantum, the project we tied, looks like it has a much better chance).

Looks like we're on our own.

**Comment by jiahao** [comment]
@quinnj I don't understand. The data returned is not guaranteed to be a valid UTF8 string, so typing it as `UTF8String` doesn't make sense to me. `show` is returning an error since it assumes that the `UTF8String` is valid.

**Comment by quinnj** [comment]
Right, I'm just saying that it's not like this is total broken or that you can't get binary data from a request. You *are* getting the data, it's just being typed weird, but you could still access the raw data by `result.data.data` and copy/cast it to something else.

**Comment by jiahao** [comment]
Oh, sure, I didn't mean to say that the web stuff was broken in that it couldn't get the data.

**Comment by malmaud** [comment]
I'll propose what (Python Requests)[http://www.python-requests.org/en/latest/user/quickstart/#response-content] does - internally, the `data` field will be bytes. Two different getters will be defined on `Response` that return the data as either bytes or a string.

**Comment by malmaud** [comment]
Fixed via https://github.com/JuliaWeb/Requests.jl/pull/64.
