### ISSUE TITLE
WARNING: This version of the GnuTLS library (3.2.15) is deprecated

### ISSUE THREAD

**Issue by paulanalyst** [JuliaWeb/Requests.jl#47]
How to upgrade the GnuTLS in win ? 
Paul.
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.3.6 (2015-02-17 22:12 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.update()
INFO: Initializing package repository C:\Users\SAMSUNG2\.julia\v0.3
INFO: Cloning METADATA from git://github.com/JuliaLang/METADATA.jl
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> Pkg.add("WinRPM")
INFO: Cloning cache of BinDeps from git://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of Compat from git://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of LibExpat from git://github.com/amitmurthy/LibExpat.jl.git
INFO: Cloning cache of SHA from git://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of URIParser from git://github.com/JuliaWeb/URIParser.jl.git
INFO: Cloning cache of WinRPM from git://github.com/JuliaLang/WinRPM.jl.git
INFO: Cloning cache of Zlib from git://github.com/dcjones/Zlib.jl.git
INFO: Installing BinDeps v0.3.7
INFO: Installing Compat v0.2.12
INFO: Installing LibExpat v0.0.6
INFO: Installing SHA v0.0.3
INFO: Installing URIParser v0.0.4
INFO: Installing WinRPM v0.1.6
INFO: Installing Zlib v0.1.7
INFO: Building WinRPM
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
WARNING: skipping repodata/repomd.xml, not in cache -- call WinRPM.update() to download
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/f322c990
9de4fe377ec69678ced90b9b9ab17757d24d63ed94b36477a93e84f9-primary.xml.gz
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/65d3ceb5
78b1243de965b54166774344236de22759295f438bb3302cbb42c5e1-primary.xml.gz
INFO: Packages to install: libgcc_s_seh1, libssp0, libstdc++6, libquadmath0, libgfortran3
INFO: Downloading: libgcc_s_seh1
INFO: Extracting: libgcc_s_seh1
INFO: Downloading: libssp0
INFO: Extracting: libssp0
INFO: Downloading: libstdc++6
INFO: Extracting: libstdc++6
INFO: Downloading: libquadmath0
INFO: Extracting: libquadmath0
INFO: Downloading: libgfortran3
INFO: Extracting: libgfortran3
INFO: Complete
INFO: Updated Julia's gcc dlls, you may need to restart Julia for some WinRPM packages to work.
INFO: Package database updated

julia> WinRPM.update()
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove

julia> using WinRPM

julia> WinRPM.search("Requests")
WinRPM Package Set:
  <empty>

julia> Pkg.add("Requests")
INFO: Cloning cache of Codecs from git://github.com/dcjones/Codecs.jl.git
INFO: Cloning cache of Dates from git://github.com/quinnj/Dates.jl.git
INFO: Cloning cache of GnuTLS from git://github.com/JuliaWeb/GnuTLS.jl.git
INFO: Cloning cache of HttpCommon from git://github.com/JuliaWeb/HttpCommon.jl.git
INFO: Cloning cache of HttpParser from git://github.com/JuliaWeb/HttpParser.jl.git
INFO: Cloning cache of JSON from git://github.com/JuliaLang/JSON.jl.git
INFO: Cloning cache of Nettle from git://github.com/staticfloat/Nettle.jl.git
INFO: Cloning cache of Requests from git://github.com/JuliaWeb/Requests.jl.git
INFO: Installing Codecs v0.1.3
INFO: Installing Dates v0.3.2
INFO: Installing GnuTLS v0.0.3
INFO: Installing HttpCommon v0.0.12
INFO: Installing HttpParser v0.0.10
INFO: Installing JSON v0.4.1
INFO: Installing Nettle v0.1.8
INFO: Installing Requests v0.0.8
INFO: Building WinRPM
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml
INFO: Building Nettle
INFO: Updating WinRPM package list
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.1//repodata/repomd.x
ml
INFO: Downloading http://download.opensuse.org/repositories/windows:/mingw:/win64/openSUSE_13.1//repodata/repomd.x
ml
INFO: Packages to install: libnettle-4-6
INFO: Downloading: libnettle-4-6
INFO: Extracting: libnettle-4-6
INFO: Complete
INFO: Building GnuTLS
INFO: Packages to install: libffi6, libtasn1-6, libp11-kit0, zlib1, libgmp10, libhogweed-2-4, gnutls-lang, libgnut
ls28, libintl8, gnutls
INFO: Downloading: libffi6
INFO: Extracting: libffi6
INFO: Downloading: libtasn1-6
INFO: Extracting: libtasn1-6
INFO: Downloading: libp11-kit0
INFO: Extracting: libp11-kit0
INFO: Downloading: zlib1
INFO: Extracting: zlib1
INFO: Downloading: libgmp10
INFO: Extracting: libgmp10
INFO: Downloading: libhogweed-2-4
INFO: Extracting: libhogweed-2-4
INFO: Downloading: gnutls-lang
INFO: Extracting: gnutls-lang
INFO: Downloading: libgnutls28
INFO: Extracting: libgnutls28
INFO: Downloading: libintl8
INFO: Extracting: libintl8
INFO: Downloading: gnutls
INFO: Extracting: gnutls
INFO: Complete
INFO: Building HttpParser
INFO: Attempting to Create directory C:\Users\SAMSUNG2\.julia\v0.3\HttpParser\deps\downloads
INFO: Downloading file https://julialang.s3.amazonaws.com/bin/winnt/extras/libhttp_parser.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 77835  100 77835    0     0  44939      0  0:00:01  0:00:01 --:--:-- 44939
INFO: Done downloading file https://julialang.s3.amazonaws.com/bin/winnt/extras/libhttp_parser.zip
INFO: Attempting to Create directory C:\Users\SAMSUNG2\.julia\v0.3\HttpParser
INFO: Directory C:\Users\SAMSUNG2\.julia\v0.3\HttpParser already created
INFO: Attempting to Create directory C:\Users\SAMSUNG2\.julia\v0.3\HttpParser\deps\usr

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\SAMSUNG2\.julia\v0.3\HttpParser\deps\downloads\libhttp_parser.zip

Extracting  usr\lib
Extracting  usr\lib\libhttp_parser32.dll
Extracting  usr\lib\libhttp_parser64.dll

Everything is Ok

Folders: 1
Files: 2
Size:       222605
Compressed: 77835
INFO: Package database updated

julia> WinRPM.search("Requests")
WinRPM Package Set:
  <empty>

julia> using Requests
WARNING: This version of the GnuTLS library (3.2.15) is deprecated
and contains known security vulnerabilities. Please upgrade to a
more recent version.

julia>

**Comment by sbromberger** [comment]
Is there a way to remove a package built by WinRPM? If so, I'd try doing a `Pkg.rm("GnuTLS")`, then removing the WinRPM package and any cache files (for both Pkg:GnuTLS and WinRPM:GnuTLS), then doing another `Pkg.update()`, and then a `Pkg.add("GnuTLS")` to force a redownload / rebuild of WinRPM:GnuTLS.

It could also be that that version of GnuTLS is the latest in WinRPM, in which case you must decide whether or not what your doing can tolerate a package with known vulnerabilities.

**Comment by paulanalyst** [comment]
Ok, like below. Big Thx.

julia> Pkg.rm("GnuTLS")
INFO: Removing GnuTLS (unregistered)

julia> Pkg.update()
INFO: Updating METADATA...
INFO: Computing changes...
INFO: Installing GnuTLS v0.0.3
INFO: Building LibCURL
INFO: Updating WinRPM package list
INFO: Downloading http://download.opensuse.org/re
ml
INFO: Downloading http://download.opensuse.org/re
ml
INFO: Building WinRPM
INFO: Downloading http://download.opensuse.org/re
ml
INFO: Downloading http://download.opensuse.org/re
ml
INFO: Building Nettle
INFO: Building GnuTLS

julia> Pkg.add("GnuTLS")
INFO: No packages to install, update or remove
INFO: Package database updated

julia> using Requests

julia> get("http://httpbin.org/get")
Response(200 OK, 12 Headers, 250 Bytes in Body)

julia> post("http://httpbin.org/post")
Response(200 OK, 12 Headers, 314 Bytes in Body)

julia> put("http://httpbin.org/put")
Response(200 OK, 12 Headers, 313 Bytes in Body)

julia> delete("http://httpbin.org/delete")
Response(200 OK, 12 Headers, 316 Bytes in Body)

julia> options("http://httpbin.org/get")
Response(200 OK, 15 Headers, 0 Bytes in Body)

julia>

W dniu 2015-02-28 o 17:35, Seth Bromberger pisze:

**Comment by sbromberger** [comment]
Just as an FYI, you're not actually doing anything that requires TLS there so it's safe to ignore the warning in any case.

**Comment by catawbasam** [comment]
I've seen a similar warning under RHEL, and have been led to understand that security fixes are patched back into the old version that is part of the distribution, so the warnings are a false alarm.

**Comment by malmaud** [comment]
It doesn't sound like this issue has any action items for Requests.jl. But please reopen if that's not the case.
