### ISSUE TITLE
Accept header changed on post

### ISSUE THREAD

**Issue by amsimms** [JuliaWeb/Requests.jl#48]
I'm attempting to connect to a web service interface that can produce results as sparql-results+json (i.e. "Accept" => "sparql-results+json").  The same code works fine with other accept content types, it is though "sparql-results+json" is not considered valid and either removed or altered.  

<pre>

cred = "Basic $(base64("anonymous:anonymous"))"

heads = { "Authorization" => cred
          #, "Accept" => "text/turtle"  # works
          #, "Accept" => "application/rdf+xml"  # works
          , "Accept" => "application/sparql-results+json" # fails
        }

result = post(URI(url); data = query, headers = heads )
println("Headers: $(heads)")
println("Result headers: $(result.headers)")
</pre>

Sample result: application/sparql-results+json (fails)

<pre>

Headers: {"Accept"=>"application/sparql-results+json","Authorization"=>"Basic YW5vbnltb3VzOmFub255bW91cw=="}
Result headers: ["http_major"=>"1","Content-Length"=>"0","Content-Type"=>"text/html; charset=utf-8","Date"=>"Mon, 09 Mar 2015 21:45:22 GMT","Content-Language"=>"en","http_minor"=>"1","Keep-Alive"=>"1","Server"=>"Julia/0.3.4","status_code"=>"406"]

</pre>

Sample result if with "application/rdf+xml" (success)

<pre>

Headers: {"Accept"=>"application/rdf+xml","Authorization"=>"Basic YW5vbnltb3VzOmFub255bW91cw=="}
Result headers: ["Transfer-Encoding"=>"chunked","http_major"=>"1","Content-Type"=>"application/rdf+xml","Date"=>"Mon, 09 Mar 2015 21:40:20 GMT","Content-Language"=>"en","http_minor"=>"1","Keep-Alive"=>"1","Server"=>"Julia/0.3.4","status_code"=>"200"]

</pre>

**Comment by wildart** [comment]
More likely your request is wrong. The status code is 406 (Not Acceptable). Maybe some additional parameters or headers required to be set for this type.

**Comment by malmaud** [comment]
@amsimms Please reopen if you still believe this is a bug in Requests.jl.
