### ISSUE TITLE
Latest version doesn't work on 0.3.2?

### ISSUE THREAD

**Issue by cormullion** [JuliaWeb/Requests.jl#49]
I accidentally updated all packages (`Pkg.update()`) and I think that the latest version of Requests.jl might not be working, with errors such as:

    ERROR: getaddrinfo callback: unknown node or service (EAI_NONAME)
      in getaddrinfo at socket.jl:538

The new version contains this changed function:

    function render(request::Request)
        join(@compat [
            request.method*" "*(isempty(request.resource)?"/":request.resource)*" HTTP/1.1";
            map(h->(h*": "*request.headers[h]),collect(keys(request.headers)));
            "";
            request.data],CRLF)
    end

which replaces the old version:

    function render(request::Request)
       join([
           request.method*" "*(isempty(request.resource)?"/":request.resource)*" HTTP/1.1",
           map(h->(h*": "*request.headers[h]),collect(keys(request.headers))),
          "",
           request.data],CRLF)
    end

If I swap the old version of the function back in, it works again.

I wish I understood what was going on, then I'd be able to suggest a fix, rather than just hard-wire my version to work again... :)

**Comment by quinnj** [comment]
Should be fixed. I had pushed a bad commit the other day and hadn't pushed my new fix for it.

**Comment by cormullion** [comment]
@quinnj Wow that's quick...! :) Thanks!
