### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/Requests.jl#51]
Every once in a while when I have some long-running `post` requests, I get the following
```julia
ERROR: write: broken pipe (EPIPE)
 in wait at ./task.jl:305
 in stream_wait at ./stream.jl:273
 in uv_write at stream.jl:754
 in buffer_or_write at stream.jl:767
 in write at stream.jl:814
 in write_ptr at /Users/jacobquinn/.julia/v0.4/GnuTLS/src/GnuTLS.jl:307
 in write at /Users/jacobquinn/.julia/v0.4/GnuTLS/src/GnuTLS.jl:373
 in write at utf8.jl:196
 in open_stream at /Users/jacobquinn/.julia/v0.4/Requests/src/Requests.jl:223
 in open_stream at /Users/jacobquinn/.julia/v0.4/Requests/src/Requests.jl:206
 in do_request at /Users/jacobquinn/.julia/v0.4/Requests/src/Requests.jl:568
 in post at /Users/jacobquinn/.julia/v0.4/Requests/src/Requests.jl:582
 in post at /Users/jacobquinn/.julia/v0.4/Requests/src/Requests.jl:581
```
Does anybody know if this is something we should try and handle in the `Requests` library? or is it a problem of the server I'm connecting to? @Keno @staticfloat

**Comment by WestleyArgentum** [comment]
Looks like https://github.com/JuliaWeb/Requests.jl/issues/18 rearing its head again

**Comment by WestleyArgentum** [comment]
Would be interested to know what version of gnutls you have:
```
julia> using GnuTLS

julia> GnuTLS.gnutls_version
```
But I think we decided that probably wasn't the root of the problem

**Comment by malmaud** [comment]
Anyone have any additional insights at this point, or at least test cases that fairly reliably trigger this?

**Comment by quinnj** [comment]
I originally thought this was the issue I was seeing [here](https://github.com/JuliaWeb/GnuTLS.jl/pull/53), but now I don't think it's the same. In the GnuTLS.jl issue, it would eventually fail after enough https calls because it was never closing the Tcp sockets.

**Comment by malmaud** [comment]
Hmm, are we positive this isn't fixed by upgrading gnutls?

**Comment by quinnj** [comment]
I'll close for now and we can reopen if this becomes reproducible in some way.
