### ISSUE TITLE
Curl POST gives other result than Requests.jl POST?

### ISSUE THREAD

**Issue by pkofod** [JuliaWeb/Requests.jl#52]
I'm cross-posting from https://groups.google.com/forum/#!topic/julia-users/M96DSCArIds

Basically, I call
```
curl -X POST -d 'grant_type=password&username=[MYNAME]&password=[MYPASS]' --user 'CLIENTID:CLIENTSECRET' https://www.reddit.com/api/v1/access_token
```

from my terminal. This gives me an OAuth token, so I can interact with the Reddit API. It works fine. I am using it in a Reddit.jl-script/interface in Julia, so I wanted to just use Julia to fetch the token as well.

The problem is that 

```julia
enc = bytestring(encode(Base64, "CLIENTID:CLIENTSECRET"))
post(URI("https://www.reddit.com/api/v1/access_token"), "grant_type=password&username=[MYNAME]&password=[MYPASS]"; headers = Dict("Authorization" => "Basic $enc", "User-Agent" => UserAgent))
% UserAgent is a string here
```
Does not do the same thing as the curl-call from above. Am I doing something wrong here? Maybe I've just misunderstood the Requests.jl syntax.

I wanted to debug my code, but I could not find a way to print my POST request before sending it. Is this possible?

Thanks!

**Comment by WestleyArgentum** [comment]
There's no debug flag yet, but it has been discussed here: https://github.com/JuliaWeb/Requests.jl/issues/14

Unfortunately I can't test this myself right now, but I believe you could do a `println(render(req))` right before https://github.com/JuliaWeb/Requests.jl/blob/master/src/Requests.jl#L223 and maybe see what you're looking for. Hope that helps

**Comment by pkofod** [comment]
Okay, my mistake has been found! Thanks for the help. I got it working by adding: 

```julia
"Content-Type" => "application/x-www-form-urlencoded"
```

To the dictionary, to match the POST request of cURL. I guess I should read up on my HTTP-protocol knowledge to understand why!

**Comment by aviks** [comment]
To check what is being passed on the network, I always rely on [ngrep](http://ngrep.sourceforge.net/) . Like `tcpdump` etc, it relies on network capture, and thus isn't reliant on functionality within the higher level libraries. On the other hand, the output is human readable. 

Can this particular issue be closed? It doesn't seem to be a problem in this package?

**Comment by pkofod** [comment]
Thanks for the ngrep-info, and I'll close it.
