### ISSUE TITLE
Performance request

### ISSUE THREAD

**Issue by quinnj** [JuliaWeb/Requests.jl#60]
Now that @malmaud is the hero JuliaWeb needs, I thought I'd put in a request (pun intended).

In the past, trying to use `Requests.get` was excruciatingly slow when trying to download large files. Below is a quick benchmark on a 8.6 zipped CSV file (publicly available). The difference isn't huge, but I'm also wondering if the slowness I've experience in the past is due to https and having to go through GnuTLS. I'll try to figure out another benchmark to show an https call.

```julia
julia> @time Requests.get("http://seanlahman.com/files/database/lahman-csv_2015-01-24.zip")
  7.701232 seconds (5.64 M allocations: 1.770 GB, 3.43% gc time)
Response(200 OK, 12 Headers, 8614880 Bytes in Body)

julia> @time readall(`curl -sS http://seanlahman.com/files/database/lahman-csv_2015-01-24.zip`);
  4.748406 seconds (9.60 k allocations: 33.613 MB, 0.42% gc time)
```

**Comment by malmaud** [comment]
Fixed in https://github.com/JuliaWeb/Requests.jl/pull/64. Requests is actually a bit faster than curl now.
