### ISSUE TITLE
Could not import Base.put

### ISSUE THREAD

**Issue by cormullion** [JuliaWeb/Requests.jl#62]
I'm investigating version 0.4, just spotted this - do I have to update something else?:

                   _
       _       _ _(_)_     |  A fresh approach to technical computing
      (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
       _ _   _| |_  __ _   |  Type "?help" for help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 0.4.0-dev+6991 (2015-08-26 04:02 UTC)
     _/ |\__'_|_|_|\__'_|  |  Commit 811a977 (0 days old master)
    |__/                   |  x86_64-apple-darwin13.4.0

    julia> using Requests
    WARNING: could not import Base.put into Requests

    julia> Pkg.status()
    2 required packages:
     - JSON                          0.4.5
     - Requests                      0.0.8
    11 additional packages:
     - BinDeps                       0.3.15
     - Codecs                        0.1.4
     - Compat                        0.6.0
     - Dates                         0.4.4
     - GnuTLS                        0.0.4
     - Homebrew                      0.1.16
     - HttpCommon                    0.0.12
     - HttpParser                    0.0.11
     - Nettle                        0.1.10
     - SHA                           0.1.1
     - URIParser                     0.0.5

By the way, these warnings (in case you've not seen them recently):

     WARNING: [a,b,...] concatenation is deprecated; use [a;b;...] instead
     in depwarn at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
     in oldstyle_vcat_warning at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
     in vect at abstractarray.jl:38

     WARNING: int(x) is deprecated, use Int(x) instead.
     in depwarn at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib
     in int at /Applications/Julia-0.4.0.app/Contents/Resources/julia/lib/julia/sys.dylib

**Comment by StefanKarpinski** [comment]
Requests definitely should not be punning on these unrelated functions methods from Base.

**Comment by quinnj** [comment]
You need to run `Pkg.update()`, @malmaud already fixed this.

**Comment by cormullion** [comment]
Like this:

    julia> Pkg.update()
    INFO: Updating METADATA...
    INFO: Computing changes...
    INFO: No packages to install, update or remove

    julia> exit()
    $ /Applications/Julia-0.4.0.app/Contents/Resources/julia/bin/julia
                   _
       _       _ _(_)_     |  A fresh approach to technical computing
      (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
       _ _   _| |_  __ _   |  Type "?help" for help.
      | | | | | | |/ _` |  |
      | | |_| | | | (_| |  |  Version 0.4.0-dev+6991 (2015-08-26 04:02 UTC)
     _/ |\__'_|_|_|\__'_|  |  Commit 811a977 (0 days old master)
    |__/                   |  x86_64-apple-darwin13.4.0

    julia> using Requests
    WARNING: could not import Base.put into Requests

Looks like something isn't being updated by Pkg.update().

**Comment by malmaud** [comment]
Try `Pkg.checkout("Requests, "master")`

**Comment by cormullion** [comment]
>Try `Pkg.checkout("Requests, "master")`

That works, I think!

**Comment by malmaud** [comment]
Great!
