### ISSUE TITLE
'get' just started returning erroneously formatted data

### ISSUE THREAD

**Issue by ianshmean** [JuliaWeb/Requests.jl#66]
Yesterday all worked as expected. The following code would return 'object' as a JSON array.
Today line 3 fails with: 'type: typeassert: expected String, got Array{Uint8,1}'

I just wanted to check whether there's any change at this end. My url appears to be returning the same data when run in a browser.

edit: I'm running in juliabox.org and this occurs with both a fresh session and an updated session (with Pkg.update() )

    resp = get(url)
    println(resp.data)
    object = JSON.parse(resp.data::String; ordered=true);

**Comment by ianshmean** [comment]
To use a specific example:
    resp = get("http://httpbin.org/get")
    object = JSON.parse(resp.data::String; ordered=true);
returns:
    type: typeassert: expected String, got Array{Uint8,1}
    while loading In[24], in expression starting on line 2

**Comment by ianshmean** [comment]
The error doesn't occur in Jula 0.4.0-dev

    resp = get("http://httpbin.org/get")
    object = JSON.parse(resp.data::String);
    println(object)

Returns:
Julia 0.4.0-dev

    Dict{AbstractString,Any}("headers"=>Dict{AbstractString,Any}("Host"=>"httpbin.org","Accept"=>"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8","User-Agent"=>"Requests.jl/0.0.0"),"args"=>Dict{AbstractString,Any}(),"url"=>"http://httpbin.org/get","origin"=>"xxxxx")

Julia 0.3.11

    type: typeassert: expected String, got Array{Uint8,1}
    while loading In[6], in expression starting on line 2

**Comment by malmaud** [comment]
In a recent update to Request, `resp.data` has changed to `Vector{UInt8}` from `String`. Use `object = Requests.json(resp)` now.

**Comment by ianshmean** [comment]
ok, thanks @malmaud  
Is there ordering functionality in `Requests.json()` ? i.e. like `JSON.parse(resp.data::String; ordered=true)`

**Comment by malmaud** [comment]
Not at the moment, although I'll add that soon. You can get back a String form of the data using `Requests.text(resp)` and then pass that to `JSON.parse`.

**Comment by ianshmean** [comment]
Perfect, thanks

**Comment by malmaud** [comment]
You are welcome
