### ISSUE TITLE
Wont build in Julia 0.3.11

### ISSUE THREAD

**Issue by josep2** [JuliaWeb/Requests.jl#69]
julia> Pkg.build("Requests")
INFO: Building HttpParser

julia> using Requests
ERROR: __precompile__ not defined
 in include at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.11.app/Contents/Resources/julia/lib/julia/sys.dylib
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
while loading /Users/jowanza/.julia/v0.3/Requests/src/Requests.jl, in expression starting on line 1

**Comment by malmaud** [comment]
I'm having some trouble replicating. With a fresh install of Julia 0.3.11, I can do 

```julia
Pkg.add("Requests")
using Requests
```

without issue. Can you tell me what the output of `Pkg.status()` is on your system?

**Comment by josep2** [comment]
Thanks r the quick response:

julia> Pkg.status()
14 required packages:
 - Calculus                      0.1.10
 - HttpServer                    0.0.14
 - IJulia                        0.2.5
 - Ito                           0.0.2
 - JSON                          0.4.5
 - Jewel                         1.0.5
 - JuMP                          0.10.1
 - KernelDensity                 0.1.1
 - Mamba                         0.4.12
 - MarketData                    0.2.6
 - Requests                      0.3.0+             master
 - TimeSeries                    0.5.10
 - Vega                          0.3.3+             master
 - ZMQ                           0.2.0
57 additional packages:
 - ArrayViews                    0.6.3
 - BinDeps                       0.3.15
 - Cairo                         0.2.29
 - Calendar                      0.4.3
 - Codecs                        0.1.4
 - ColorBrewer                   0.2.1
 - ColorTypes                    0.1.3
 - Colors                        0.5.2
 - Compat                        0.6.0
 - Compose                       0.3.14
 - Contour                       0.0.7
 - DataArrays                    0.2.18
 - DataFrames                    0.6.9
 - DataStructures                0.3.12
 - Dates                         0.3.2
 - Distances                     0.2.0
 - Distributions                 0.8.6
 - Docile                        0.5.18
 - DualNumbers                   0.1.3
 - FactCheck                     0.4.0
 - FixedPointNumbers             0.0.10
 - Forecastio                    0.0.0-             master (unregistered)
 - GZip                          0.2.17
 - Gadfly                        0.3.14
 - GnuTLS                        0.0.5
 - Graphics                      0.1.0
 - Graphs                        0.5.5
 - Grid                          0.3.10
 - Hexagons                      0.0.4
 - Homebrew                      0.1.16
 - HttpCommon                    0.1.2
 - HttpParser                    0.0.13
 - ICU                           0.4.4
 - ImmutableArrays               0.0.10
 - Iterators                     0.1.8
 - JuliaParser                   0.6.2
 - LNR                           0.0.1
 - Lazy                          0.10.0
 - Loess                         0.0.3
 - MacroTools                    0.2.0
 - MathProgBase                  0.3.17
 - NaNMath                       0.1.0
 - Nettle                        0.1.10
 - Optim                         0.4.2
 - PDMats                        0.3.5
 - REPLCompletions               0.0.3
 - Reexport                      0.0.3
 - Requires                      0.1.3
 - ReverseDiffSparse             0.2.10
 - SHA                           0.1.1
 - Showoff                       0.0.4
 - SortingAlgorithms             0.0.5
 - StatsBase                     0.7.2
 - StatsFuns                     0.1.3
 - URIParser                     0.0.7
 - WoodburyMatrices              0.1.1
 - Zlib                          0.1.9

**Comment by malmaud** [comment]
The issue is that you have the 'master' branch checked out for Requests, which isn't compatible with Julia 0.3. Call `Pkg.free("Requests")`

**Comment by malmaud** [comment]
Please reopen if you're still having trouble.
