### ISSUE TITLE
Add NEWS.md file

### ISSUE THREAD

**Issue by milktrader** [JuliaWeb/Requests.jl#72]
Recent changes to the semantics of `.data` has broken Quand.jll and I'm not sure what version to use as the ceiling.

**Comment by malmaud** [comment]
Ya, that's a good idea.

**Comment by milktrader** [comment]
Thanks! I just started doing it myself.

**Comment by malmaud** [comment]
Closed in https://github.com/JuliaWeb/Requests.jl/commit/9bca91bfed006d94edbf79761ebc3cb2909cdd9b.
