### ISSUE TITLE
SNI support?

### ISSUE THREAD

**Issue by philipithomas** [JuliaWeb/Requests.jl#73]
The packaged GnuTLS seems to be of an old version, so I can't complete requests to a website that uses the latest TLS SNI technology (e.g. any website protected by cloudflare). Do you have advice on getting this to work?

**Comment by malmaud** [comment]
We've recently upgraded to MbedTLS (formally PolarSSL). It's not officially tagged quite yet (it will be in the next few days), but you can try it out now by checking out the 'master' branch of Requests and it's dependencies:

```julia
Pkg.checkout("HttpCommon")
Pkg.checkout("MbedTLS")
Pkg.checkout("Requests")
Pkg.build("Requests")
```

**Comment by malmaud** [comment]
Closed via https://github.com/JuliaWeb/Requests.jl/commit/d50f6b53339cd2927c48ea2719dffe65e2bb436f. SNI will work now if you check out the master version of the packages.
