### ISSUE TITLE
Issue logging in via post() 

### ISSUE THREAD

**Issue by crbinz** [JuliaWeb/Requests.jl#76]
My issue is with [this site](https://www.space-track.org/documentation#/howto). Specifically, I need to use the ajaxauth/login address for logging in, and I can't get this to work:

```
resp = post("https://www.space-track.org/ajaxauth/login",data="identity=username&password=password")
Response(401 Unauthorized, 11 Headers, 69 Bytes in Body)
```

I tried this with the Python requests package, and it worked as expected:

```
cred = {'identity':'username' , 'password':'password'}
r = requests.post("https://www.space-track.org/ajaxauth/login",data = cred)
```
(result is Response 200)

the body of the request is the same (except that password comes before username):

```
julia>ASCIIString(resp.requests[1].data)
"identity=username&password=password"
```

Python:
```
>>>r.request.body
'password=password&identity=username'
```

I also tried switching the order of `password` and `identity`, to no avail. I am not even sure this is an issue with `Requests.jl`, but I figured I'd start here.

Thanks.

**Comment by malmaud** [comment]
Closed by https://github.com/JuliaWeb/Requests.jl/commit/52a144979be9cf62c3080bd82cb3bc5ecab95bc9

**Comment by malmaud** [comment]
The latest version of Requests.jl will now work with the same API as the Python version:

```julia
post(url, data=Dict("identity"=>..., "password"=>...)
```

If you can't upgrade to master, then you manually fix this by calling
```julia
post(url, data="identity=a%40b.com&password=...", headers=Dict("Content-type"=>"application/x-www-form-urlencoded")
```
Note that in this manual version, you have to manually URL-escape the data, meaning replacing '%' with '%40' in the identity email address.

**Comment by malmaud** [comment]
Also thanks for bringing this to my attention.

**Comment by crbinz** [comment]
Thank you for addressing this so quickly. I try to checkout the latest master, but then I get the following errors upon `using Requests`:

```
ERROR: InitError: UndefVarError: add_source! not defined
 in get_default_tls_config at /Users/cbinz/.julia/v0.4/Requests/src/streaming.jl:99
 in __init_streaming__ at /Users/cbinz/.julia/v0.4/Requests/src/streaming.jl:188
 in __init__ at /Users/cbinz/.julia/v0.4/Requests/src/Requests.jl:28
 in _require_from_serialized at loading.jl:84
 in _require_from_serialized at /Applications/Julia-0.4.0-rc2.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.0-rc2.app/Contents/Resources/julia/lib/julia/sys.dylib
during initialization of module Requests
```

**Comment by malmaud** [comment]
You also need the master of its dependencies, `HttpCommon` and `MbedTLS`.

**Comment by crbinz** [comment]
That did the trick, thanks again!

**Comment by malmaud** [comment]
No problem.
