### ISSUE TITLE
Requests.head( url )

### ISSUE THREAD

**Issue by mdcfrancis** [JuliaWeb/Requests.jl#78]
Requests.head appears to hang and never come back, I''ll take a look, but is this a known issue ?

**Comment by mdcfrancis** [comment]
Since HEAD has no body it is waiting 
```
if( verb != "HEAD") # HEAD has no body
      response.data = readbytes(response_stream)
end
```

**Comment by malmaud** [comment]
Thanks for the report and fix. I think to make things a bit more robust, it's better to write that code in a way that can always deal with a missing body instead of specializing it for a particular verb. PR welcome, or I'll get to myself in the next few days.

**Comment by mdcfrancis** [comment]
Agreed - I'll have a look.

**Comment by mdcfrancis** [comment]
Tracing this through - it appears that it is required to special case the HEAD request (this is the only one so documented ) - the following is from https://github.com/nodejs/http-parser/blob/master/http_parser.h - pull request on its way 
```
/* Callbacks should return non-zero to indicate an error. The parser will
 * then halt execution.
 *
 * The one exception is on_headers_complete. In a HTTP_RESPONSE parser
 * returning '1' from on_headers_complete will tell the parser that it
 * should not expect a body. This is used when receiving a response to a
 * HEAD request which may contain 'Content-Length' or 'Transfer-Encoding:
 * chunked' headers that indicate the presence of a body.
 *
 * http_data_cb does not return data chunks. It will be called arbitrarily
 * many times for each string. E.G. you might get 10 callbacks for "on_url"
 * each providing just a few characters more data.
 */
```

**Comment by mdcfrancis** [comment]
https://github.com/JuliaWeb/Requests.jl/pull/79

**Comment by malmaud** [comment]
Thanks!
