### ISSUE TITLE
Proxy support?

### ISSUE THREAD

**Issue by amellnik** [JuliaWeb/Requests.jl#80]
It looks like Requests doesn't look at the http_proxy or https_proxy environment variables, or have any way to pass these to it.  Is there any way to include this?

**Comment by malmaud** [comment]
We should definitely have that; it's just a matter of someone carving out the time to do it.

**Comment by malmaud** [comment]
Can you test the new `proxy` branch and let me know if that works for you? It supports `http_proxy` but not `https_proxy` (for now).

**Comment by amellnik** [comment]
It works great -- I am very impressed!

**Comment by malmaud** [comment]
Great! I added support for `https_proxy` too.
