### ISSUE TITLE
precompile issue?

### ISSUE THREAD

**Issue by sbromberger** [JuliaWeb/Requests.jl#83]
I'm getting precompile failures with GeoIP, and I think they're in the Requests precompilation. From travis:

https://travis-ci.org/JuliaWeb/GeoIP.jl/jobs/87342701#L838-L856

Also ref https://github.com/fhs/ZipFile.jl/issues/22

**Comment by malmaud** [comment]
We should just switch to libz.

**Comment by malmaud** [comment]
Closed via https://github.com/JuliaWeb/Requests.jl/commit/45480d1ea55ba27844e8f002fe1e2ad6c25b7893
