### ISSUE TITLE
warnings on method definition overrides

### ISSUE THREAD

**Issue by sebastiang** [JuliaWeb/Requests.jl#88]
And, from what I can tell, some non-deterministic behavior. 

    WARNING: Method definition get(AbstractString) in module Requests at /Users/sebastian/.julia/v0.4/Requests/src/Requests.jl:394 overwritten in module HTTPC at /Users/sebastian/.julia/v0.4/HTTPClient/src/HTTPC.jl:534.
    WARNING: Method definition get(Array, AbstractString) in module Requests overwritten in module HTTPC.
    WARNING: Method definition get(AbstractString) in module HTTPC at /Users/sebastian/.julia/v0.4/HTTPClient/src/HTTPC.jl:534 overwritten in module Requests at /Users/sebastian/.julia/v0.4/Requests/src/Requests.jl:394.
    WARNING: Method definition get(Array, AbstractString) in module HTTPC overwritten in module Requests.

**Comment by sebastiang** [comment]
After running code that uses `Requests.jl`, other code which worked successfully before now causes segfaults. Something about the method overrides is causing precompilation to create corrupted data structures.

**Comment by malmaud** [comment]
It looks like HTTPClient and Requests, which are two independent (and essentially redundant) packages, both add conflicting new methods to Base. That sometimes happens.

That shouldn't cause segfaults in and of itself - maybe that's a bug in Julia, which should be reported there.

**Comment by sebastiang** [comment]
That’s the impression I get.

**Comment by malmaud** [comment]
Anyways, doesn't seem like there is an action item for Requests here, so I'll close for now.
