### ISSUE TITLE
Precompile of Requests failing in Julia 0.4.2

### ISSUE THREAD

**Issue by ianshmean** [JuliaWeb/Requests.jl#90]
I'm trying to load the following but I get stuck at Requests and hit the error below. DataStructures also gives me the same error if I reorder them in the using instruction
Any ideas?

--
`using Compat, Requests, DataStructures, JSON, PyPlot, LsqFit, HypothesisTests`

error:

INFO: Precompiling module Requests...
INFO: Recompiling stale cache file /opt/julia_packages/.julia/lib/v0.4/URIParser.ji for module URIParser.
ERROR: LoadError: unlink: read-only file system (EROFS)
 in unlink at fs.jl:102
 in rm at file.jl:59
 in create_expr_cache at loading.jl:330
 in recompile_stale at loading.jl:461
 in _require_from_serialized at loading.jl:83
 in _require_from_serialized at ./loading.jl:109
 in require at ./loading.jl:219
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:304
 [inlined code] from none:2
 in anonymous at no file:0
 in process_options at ./client.jl:257
 in _start at ./client.jl:378
while loading /home/juser/.julia/v0.4/Requests/src/Requests.jl, in expression starting on line 11

**Comment by malmaud** [comment]
I don't think this error has anything to do with Requests per se - better to file it as a bug in precompilation in the main Julia repo.

**Comment by ianshmean** [comment]
Thanks for the pointer, you were correct! It's been discussed and addressed here https://github.com/JuliaLang/julia/issues/14368
