### ISSUE TITLE
Human-readable status codes

### ISSUE THREAD

**Issue by hayd** [JuliaWeb/Requests.jl#95]
It's be nice to have this available,but I'm not sure on a good dict/method name.

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes

That is 200 => "OK", 402 => "Payment Required" etc.

Happy to put something together.

**Comment by malmaud** [comment]
behold https://github.com/JuliaWeb/HttpCommon.jl/blob/master/src/status.jl

**Comment by hayd** [comment]
How did I miss that?? Thanks!
